<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage 
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="dictionnaire"
    nsURI="http://dictionnaire.source"
    nsPrefix="dic">

    <!-- Classe Dictionnaire -->
    <eClassifiers xsi:type="ecore:EClass" name="Dictionnaire">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="editeur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="nomsPropres" upperBound="-1" containment="true" eType="#//NomPropre"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="motsCommuns" upperBound="-1" containment="true" eType="#//MotCommun"/>
    </eClassifiers>

    <!-- Classe NomPropre -->
    <eClassifiers xsi:type="ecore:EClass" name="NomPropre">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="explication" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <!-- Classe MotCommun -->
    <eClassifiers xsi:type="ecore:EClass" name="MotCommun">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="explication" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="synonyme" eType="#//MotCommun"/>
    </eClassifiers>

</ecore:EPackage>
